// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logic.proto

package netproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 错误码
type E_Code int32

const (
	E_Code_E_ERROR                 E_Code = 0
	E_Code_E_OK                    E_Code = 1
	E_Code_E_RELOGIN               E_Code = 2
	E_Code_E_NONE_EXIST            E_Code = 3
	E_Code_E_UNKNOWN               E_Code = 4
	E_Code_E_SERVER_INTERNAL_ERROR E_Code = 5
	E_Code_E_INVALID_PARAM         E_Code = 6
	E_Code_E_INVALID_OPT           E_Code = 7
)

var E_Code_name = map[int32]string{
	0: "E_ERROR",
	1: "E_OK",
	2: "E_RELOGIN",
	3: "E_NONE_EXIST",
	4: "E_UNKNOWN",
	5: "E_SERVER_INTERNAL_ERROR",
	6: "E_INVALID_PARAM",
	7: "E_INVALID_OPT",
}
var E_Code_value = map[string]int32{
	"E_ERROR":                 0,
	"E_OK":                    1,
	"E_RELOGIN":               2,
	"E_NONE_EXIST":            3,
	"E_UNKNOWN":               4,
	"E_SERVER_INTERNAL_ERROR": 5,
	"E_INVALID_PARAM":         6,
	"E_INVALID_OPT":           7,
}

func (x E_Code) String() string {
	return proto.EnumName(E_Code_name, int32(x))
}
func (E_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_logic_e158a3ba68c28799, []int{0}
}

// 前100号的消息留给系统用
type EMsgIds int32

const (
	EMsgIds_ECS_None EMsgIds = 0
	// 心跳
	EMsgIds_ECS_Tick  EMsgIds = 101
	EMsgIds_ESC_Tick  EMsgIds = 102
	EMsgIds_ECS_Login EMsgIds = 103
	EMsgIds_ESC_Login EMsgIds = 104
)

var EMsgIds_name = map[int32]string{
	0:   "ECS_None",
	101: "ECS_Tick",
	102: "ESC_Tick",
	103: "ECS_Login",
	104: "ESC_Login",
}
var EMsgIds_value = map[string]int32{
	"ECS_None":  0,
	"ECS_Tick":  101,
	"ESC_Tick":  102,
	"ECS_Login": 103,
	"ESC_Login": 104,
}

func (x EMsgIds) String() string {
	return proto.EnumName(EMsgIds_name, int32(x))
}
func (EMsgIds) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_logic_e158a3ba68c28799, []int{1}
}

// 心跳
type CS_Tick struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_Tick) Reset()         { *m = CS_Tick{} }
func (m *CS_Tick) String() string { return proto.CompactTextString(m) }
func (*CS_Tick) ProtoMessage()    {}
func (*CS_Tick) Descriptor() ([]byte, []int) {
	return fileDescriptor_logic_e158a3ba68c28799, []int{0}
}
func (m *CS_Tick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_Tick.Unmarshal(m, b)
}
func (m *CS_Tick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_Tick.Marshal(b, m, deterministic)
}
func (dst *CS_Tick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_Tick.Merge(dst, src)
}
func (m *CS_Tick) XXX_Size() int {
	return xxx_messageInfo_CS_Tick.Size(m)
}
func (m *CS_Tick) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_Tick.DiscardUnknown(m)
}

var xxx_messageInfo_CS_Tick proto.InternalMessageInfo

type SC_Tick struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SC_Tick) Reset()         { *m = SC_Tick{} }
func (m *SC_Tick) String() string { return proto.CompactTextString(m) }
func (*SC_Tick) ProtoMessage()    {}
func (*SC_Tick) Descriptor() ([]byte, []int) {
	return fileDescriptor_logic_e158a3ba68c28799, []int{1}
}
func (m *SC_Tick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_Tick.Unmarshal(m, b)
}
func (m *SC_Tick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_Tick.Marshal(b, m, deterministic)
}
func (dst *SC_Tick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_Tick.Merge(dst, src)
}
func (m *SC_Tick) XXX_Size() int {
	return xxx_messageInfo_SC_Tick.Size(m)
}
func (m *SC_Tick) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_Tick.DiscardUnknown(m)
}

var xxx_messageInfo_SC_Tick proto.InternalMessageInfo

// 登录
type CS_Login struct {
	Token                string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_Login) Reset()         { *m = CS_Login{} }
func (m *CS_Login) String() string { return proto.CompactTextString(m) }
func (*CS_Login) ProtoMessage()    {}
func (*CS_Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_logic_e158a3ba68c28799, []int{2}
}
func (m *CS_Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_Login.Unmarshal(m, b)
}
func (m *CS_Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_Login.Marshal(b, m, deterministic)
}
func (dst *CS_Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_Login.Merge(dst, src)
}
func (m *CS_Login) XXX_Size() int {
	return xxx_messageInfo_CS_Login.Size(m)
}
func (m *CS_Login) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_Login.DiscardUnknown(m)
}

var xxx_messageInfo_CS_Login proto.InternalMessageInfo

func (m *CS_Login) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SC_Login struct {
	Code                 E_Code   `protobuf:"varint,1,opt,name=code,enum=netproto.E_Code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SC_Login) Reset()         { *m = SC_Login{} }
func (m *SC_Login) String() string { return proto.CompactTextString(m) }
func (*SC_Login) ProtoMessage()    {}
func (*SC_Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_logic_e158a3ba68c28799, []int{3}
}
func (m *SC_Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SC_Login.Unmarshal(m, b)
}
func (m *SC_Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SC_Login.Marshal(b, m, deterministic)
}
func (dst *SC_Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SC_Login.Merge(dst, src)
}
func (m *SC_Login) XXX_Size() int {
	return xxx_messageInfo_SC_Login.Size(m)
}
func (m *SC_Login) XXX_DiscardUnknown() {
	xxx_messageInfo_SC_Login.DiscardUnknown(m)
}

var xxx_messageInfo_SC_Login proto.InternalMessageInfo

func (m *SC_Login) GetCode() E_Code {
	if m != nil {
		return m.Code
	}
	return E_Code_E_ERROR
}

type CS_None struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CS_None) Reset()         { *m = CS_None{} }
func (m *CS_None) String() string { return proto.CompactTextString(m) }
func (*CS_None) ProtoMessage()    {}
func (*CS_None) Descriptor() ([]byte, []int) {
	return fileDescriptor_logic_e158a3ba68c28799, []int{4}
}
func (m *CS_None) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CS_None.Unmarshal(m, b)
}
func (m *CS_None) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CS_None.Marshal(b, m, deterministic)
}
func (dst *CS_None) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CS_None.Merge(dst, src)
}
func (m *CS_None) XXX_Size() int {
	return xxx_messageInfo_CS_None.Size(m)
}
func (m *CS_None) XXX_DiscardUnknown() {
	xxx_messageInfo_CS_None.DiscardUnknown(m)
}

var xxx_messageInfo_CS_None proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CS_Tick)(nil), "netproto.CS_Tick")
	proto.RegisterType((*SC_Tick)(nil), "netproto.SC_Tick")
	proto.RegisterType((*CS_Login)(nil), "netproto.CS_Login")
	proto.RegisterType((*SC_Login)(nil), "netproto.SC_Login")
	proto.RegisterType((*CS_None)(nil), "netproto.CS_None")
	proto.RegisterEnum("netproto.E_Code", E_Code_name, E_Code_value)
	proto.RegisterEnum("netproto.EMsgIds", EMsgIds_name, EMsgIds_value)
}

func init() { proto.RegisterFile("logic.proto", fileDescriptor_logic_e158a3ba68c28799) }

var fileDescriptor_logic_e158a3ba68c28799 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0xa9, 0x02, 0x2d, 0x03, 0xe8, 0xb8, 0x9a, 0x68, 0xe2, 0x85, 0x10, 0x0f, 0x86, 0x03,
	0x31, 0xfa, 0x04, 0x4d, 0x9d, 0x98, 0x86, 0xb2, 0x8b, 0xbb, 0x15, 0xbd, 0x4d, 0x22, 0xac, 0x95,
	0x60, 0xba, 0x46, 0x78, 0x14, 0x1f, 0xd8, 0xb0, 0x6d, 0xe3, 0xed, 0xff, 0x76, 0xfe, 0xcc, 0x4e,
	0x3e, 0xe8, 0x7f, 0xb9, 0x62, 0xb3, 0x9a, 0x7e, 0xff, 0xb8, 0xbd, 0x13, 0x51, 0x69, 0xf7, 0x3e,
	0x8d, 0x7b, 0x10, 0x26, 0x86, 0xf3, 0xcd, 0x6a, 0x7b, 0x88, 0x26, 0xa9, 0xe2, 0x08, 0xa2, 0xc4,
	0x70, 0xe6, 0x8a, 0x4d, 0x29, 0x2e, 0xa0, 0xb3, 0x77, 0x5b, 0x5b, 0x5e, 0x05, 0xa3, 0xe0, 0xb6,
	0xa7, 0x2b, 0x18, 0xdf, 0x41, 0x64, 0x92, 0xba, 0x71, 0x03, 0xed, 0x95, 0x5b, 0x5b, 0x5f, 0x38,
	0xb9, 0xc7, 0x69, 0xb3, 0x7c, 0x4a, 0x9c, 0xb8, 0xb5, 0xd5, 0x7e, 0x5a, 0xff, 0x24, 0x5d, 0x69,
	0x27, 0xbf, 0x01, 0x74, 0xab, 0x99, 0xe8, 0x43, 0x48, 0x4c, 0x5a, 0x2b, 0x8d, 0x2d, 0x11, 0x41,
	0x9b, 0x58, 0xcd, 0x30, 0x10, 0x43, 0xe8, 0x11, 0x6b, 0xca, 0xd4, 0x53, 0x2a, 0xf1, 0x48, 0x20,
	0x0c, 0x88, 0xa5, 0x92, 0xc4, 0xf4, 0x96, 0x9a, 0x1c, 0x8f, 0xab, 0xc2, 0x8b, 0x9c, 0x49, 0xf5,
	0x2a, 0xb1, 0x2d, 0xae, 0xe1, 0x92, 0xd8, 0x90, 0x5e, 0x92, 0xe6, 0x54, 0xe6, 0xa4, 0x65, 0x9c,
	0xd5, 0x6b, 0x3b, 0xe2, 0x1c, 0x4e, 0x89, 0x53, 0xb9, 0x8c, 0xb3, 0xf4, 0x91, 0x17, 0xb1, 0x8e,
	0xe7, 0xd8, 0x15, 0x67, 0x30, 0xfc, 0x7f, 0x54, 0x8b, 0x1c, 0xc3, 0xc9, 0x33, 0x84, 0x34, 0xdf,
	0x15, 0xe9, 0x7a, 0x27, 0x06, 0x10, 0x51, 0x7d, 0x2d, 0xb6, 0x1a, 0x3a, 0xa8, 0x41, 0xeb, 0xa9,
	0x16, 0x85, 0x1f, 0xfe, 0x90, 0xc6, 0x15, 0x16, 0x1e, 0x1b, 0x31, 0xf8, 0xf9, 0xde, 0xf5, 0x22,
	0x1e, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x3e, 0xbd, 0xdd, 0x7e, 0x01, 0x00, 0x00,
}
