// Code generated by protoc-gen-go. DO NOT EDIT.
// source: playerdata.proto

package netproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PlayerDatabaseInfo struct {
	Key                  *int32    `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *BaseInfo `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PlayerDatabaseInfo) Reset()         { *m = PlayerDatabaseInfo{} }
func (m *PlayerDatabaseInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerDatabaseInfo) ProtoMessage()    {}
func (*PlayerDatabaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{0}
}
func (m *PlayerDatabaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerDatabaseInfo.Unmarshal(m, b)
}
func (m *PlayerDatabaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerDatabaseInfo.Marshal(b, m, deterministic)
}
func (dst *PlayerDatabaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerDatabaseInfo.Merge(dst, src)
}
func (m *PlayerDatabaseInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerDatabaseInfo.Size(m)
}
func (m *PlayerDatabaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerDatabaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerDatabaseInfo proto.InternalMessageInfo

func (m *PlayerDatabaseInfo) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *PlayerDatabaseInfo) GetVal() *BaseInfo {
	if m != nil {
		return m.Val
	}
	return nil
}

type PlayerInfoserverTime struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int64   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfoserverTime) Reset()         { *m = PlayerInfoserverTime{} }
func (m *PlayerInfoserverTime) String() string { return proto.CompactTextString(m) }
func (*PlayerInfoserverTime) ProtoMessage()    {}
func (*PlayerInfoserverTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{1}
}
func (m *PlayerInfoserverTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfoserverTime.Unmarshal(m, b)
}
func (m *PlayerInfoserverTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfoserverTime.Marshal(b, m, deterministic)
}
func (dst *PlayerInfoserverTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfoserverTime.Merge(dst, src)
}
func (m *PlayerInfoserverTime) XXX_Size() int {
	return xxx_messageInfo_PlayerInfoserverTime.Size(m)
}
func (m *PlayerInfoserverTime) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfoserverTime.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfoserverTime proto.InternalMessageInfo

func (m *PlayerInfoserverTime) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *PlayerInfoserverTime) GetVal() int64 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type PlayerInfoserverName struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *string  `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfoserverName) Reset()         { *m = PlayerInfoserverName{} }
func (m *PlayerInfoserverName) String() string { return proto.CompactTextString(m) }
func (*PlayerInfoserverName) ProtoMessage()    {}
func (*PlayerInfoserverName) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{2}
}
func (m *PlayerInfoserverName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfoserverName.Unmarshal(m, b)
}
func (m *PlayerInfoserverName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfoserverName.Marshal(b, m, deterministic)
}
func (dst *PlayerInfoserverName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfoserverName.Merge(dst, src)
}
func (m *PlayerInfoserverName) XXX_Size() int {
	return xxx_messageInfo_PlayerInfoserverName.Size(m)
}
func (m *PlayerInfoserverName) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfoserverName.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfoserverName proto.InternalMessageInfo

func (m *PlayerInfoserverName) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *PlayerInfoserverName) GetVal() string {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return ""
}

type BaseInfoid struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int64   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseInfoid) Reset()         { *m = BaseInfoid{} }
func (m *BaseInfoid) String() string { return proto.CompactTextString(m) }
func (*BaseInfoid) ProtoMessage()    {}
func (*BaseInfoid) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{3}
}
func (m *BaseInfoid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfoid.Unmarshal(m, b)
}
func (m *BaseInfoid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfoid.Marshal(b, m, deterministic)
}
func (dst *BaseInfoid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfoid.Merge(dst, src)
}
func (m *BaseInfoid) XXX_Size() int {
	return xxx_messageInfo_BaseInfoid.Size(m)
}
func (m *BaseInfoid) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfoid.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfoid proto.InternalMessageInfo

func (m *BaseInfoid) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *BaseInfoid) GetVal() int64 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type BaseInfoname struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *string  `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseInfoname) Reset()         { *m = BaseInfoname{} }
func (m *BaseInfoname) String() string { return proto.CompactTextString(m) }
func (*BaseInfoname) ProtoMessage()    {}
func (*BaseInfoname) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{4}
}
func (m *BaseInfoname) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfoname.Unmarshal(m, b)
}
func (m *BaseInfoname) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfoname.Marshal(b, m, deterministic)
}
func (dst *BaseInfoname) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfoname.Merge(dst, src)
}
func (m *BaseInfoname) XXX_Size() int {
	return xxx_messageInfo_BaseInfoname.Size(m)
}
func (m *BaseInfoname) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfoname.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfoname proto.InternalMessageInfo

func (m *BaseInfoname) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *BaseInfoname) GetVal() string {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return ""
}

type BaseInfolevel struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int32   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseInfolevel) Reset()         { *m = BaseInfolevel{} }
func (m *BaseInfolevel) String() string { return proto.CompactTextString(m) }
func (*BaseInfolevel) ProtoMessage()    {}
func (*BaseInfolevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{5}
}
func (m *BaseInfolevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfolevel.Unmarshal(m, b)
}
func (m *BaseInfolevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfolevel.Marshal(b, m, deterministic)
}
func (dst *BaseInfolevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfolevel.Merge(dst, src)
}
func (m *BaseInfolevel) XXX_Size() int {
	return xxx_messageInfo_BaseInfolevel.Size(m)
}
func (m *BaseInfolevel) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfolevel.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfolevel proto.InternalMessageInfo

func (m *BaseInfolevel) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *BaseInfolevel) GetVal() int32 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type BaseInfoexp struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int32   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseInfoexp) Reset()         { *m = BaseInfoexp{} }
func (m *BaseInfoexp) String() string { return proto.CompactTextString(m) }
func (*BaseInfoexp) ProtoMessage()    {}
func (*BaseInfoexp) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{6}
}
func (m *BaseInfoexp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfoexp.Unmarshal(m, b)
}
func (m *BaseInfoexp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfoexp.Marshal(b, m, deterministic)
}
func (dst *BaseInfoexp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfoexp.Merge(dst, src)
}
func (m *BaseInfoexp) XXX_Size() int {
	return xxx_messageInfo_BaseInfoexp.Size(m)
}
func (m *BaseInfoexp) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfoexp.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfoexp proto.InternalMessageInfo

func (m *BaseInfoexp) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *BaseInfoexp) GetVal() int32 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type BaseInfogold struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int32   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseInfogold) Reset()         { *m = BaseInfogold{} }
func (m *BaseInfogold) String() string { return proto.CompactTextString(m) }
func (*BaseInfogold) ProtoMessage()    {}
func (*BaseInfogold) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{7}
}
func (m *BaseInfogold) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfogold.Unmarshal(m, b)
}
func (m *BaseInfogold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfogold.Marshal(b, m, deterministic)
}
func (dst *BaseInfogold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfogold.Merge(dst, src)
}
func (m *BaseInfogold) XXX_Size() int {
	return xxx_messageInfo_BaseInfogold.Size(m)
}
func (m *BaseInfogold) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfogold.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfogold proto.InternalMessageInfo

func (m *BaseInfogold) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *BaseInfogold) GetVal() int32 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type BaseInfohead struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int32   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseInfohead) Reset()         { *m = BaseInfohead{} }
func (m *BaseInfohead) String() string { return proto.CompactTextString(m) }
func (*BaseInfohead) ProtoMessage()    {}
func (*BaseInfohead) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{8}
}
func (m *BaseInfohead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfohead.Unmarshal(m, b)
}
func (m *BaseInfohead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfohead.Marshal(b, m, deterministic)
}
func (dst *BaseInfohead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfohead.Merge(dst, src)
}
func (m *BaseInfohead) XXX_Size() int {
	return xxx_messageInfo_BaseInfohead.Size(m)
}
func (m *BaseInfohead) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfohead.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfohead proto.InternalMessageInfo

func (m *BaseInfohead) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *BaseInfohead) GetVal() int32 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type BaseInfodiamond struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int32   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseInfodiamond) Reset()         { *m = BaseInfodiamond{} }
func (m *BaseInfodiamond) String() string { return proto.CompactTextString(m) }
func (*BaseInfodiamond) ProtoMessage()    {}
func (*BaseInfodiamond) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{9}
}
func (m *BaseInfodiamond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfodiamond.Unmarshal(m, b)
}
func (m *BaseInfodiamond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfodiamond.Marshal(b, m, deterministic)
}
func (dst *BaseInfodiamond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfodiamond.Merge(dst, src)
}
func (m *BaseInfodiamond) XXX_Size() int {
	return xxx_messageInfo_BaseInfodiamond.Size(m)
}
func (m *BaseInfodiamond) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfodiamond.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfodiamond proto.InternalMessageInfo

func (m *BaseInfodiamond) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *BaseInfodiamond) GetVal() int32 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type TestListid struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int64   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestListid) Reset()         { *m = TestListid{} }
func (m *TestListid) String() string { return proto.CompactTextString(m) }
func (*TestListid) ProtoMessage()    {}
func (*TestListid) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{10}
}
func (m *TestListid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestListid.Unmarshal(m, b)
}
func (m *TestListid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestListid.Marshal(b, m, deterministic)
}
func (dst *TestListid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestListid.Merge(dst, src)
}
func (m *TestListid) XXX_Size() int {
	return xxx_messageInfo_TestListid.Size(m)
}
func (m *TestListid) XXX_DiscardUnknown() {
	xxx_messageInfo_TestListid.DiscardUnknown(m)
}

var xxx_messageInfo_TestListid proto.InternalMessageInfo

func (m *TestListid) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *TestListid) GetVal() int64 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type TestListListPrimitiveInt struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int32   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestListListPrimitiveInt) Reset()         { *m = TestListListPrimitiveInt{} }
func (m *TestListListPrimitiveInt) String() string { return proto.CompactTextString(m) }
func (*TestListListPrimitiveInt) ProtoMessage()    {}
func (*TestListListPrimitiveInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{11}
}
func (m *TestListListPrimitiveInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestListListPrimitiveInt.Unmarshal(m, b)
}
func (m *TestListListPrimitiveInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestListListPrimitiveInt.Marshal(b, m, deterministic)
}
func (dst *TestListListPrimitiveInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestListListPrimitiveInt.Merge(dst, src)
}
func (m *TestListListPrimitiveInt) XXX_Size() int {
	return xxx_messageInfo_TestListListPrimitiveInt.Size(m)
}
func (m *TestListListPrimitiveInt) XXX_DiscardUnknown() {
	xxx_messageInfo_TestListListPrimitiveInt.DiscardUnknown(m)
}

var xxx_messageInfo_TestListListPrimitiveInt proto.InternalMessageInfo

func (m *TestListListPrimitiveInt) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *TestListListPrimitiveInt) GetVal() int32 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type TestListListPrimitiveStr struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *string  `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestListListPrimitiveStr) Reset()         { *m = TestListListPrimitiveStr{} }
func (m *TestListListPrimitiveStr) String() string { return proto.CompactTextString(m) }
func (*TestListListPrimitiveStr) ProtoMessage()    {}
func (*TestListListPrimitiveStr) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{12}
}
func (m *TestListListPrimitiveStr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestListListPrimitiveStr.Unmarshal(m, b)
}
func (m *TestListListPrimitiveStr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestListListPrimitiveStr.Marshal(b, m, deterministic)
}
func (dst *TestListListPrimitiveStr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestListListPrimitiveStr.Merge(dst, src)
}
func (m *TestListListPrimitiveStr) XXX_Size() int {
	return xxx_messageInfo_TestListListPrimitiveStr.Size(m)
}
func (m *TestListListPrimitiveStr) XXX_DiscardUnknown() {
	xxx_messageInfo_TestListListPrimitiveStr.DiscardUnknown(m)
}

var xxx_messageInfo_TestListListPrimitiveStr proto.InternalMessageInfo

func (m *TestListListPrimitiveStr) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *TestListListPrimitiveStr) GetVal() string {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return ""
}

type TestListListPrimitiveCom struct {
	Key                  *int32      `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *PlayerData `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TestListListPrimitiveCom) Reset()         { *m = TestListListPrimitiveCom{} }
func (m *TestListListPrimitiveCom) String() string { return proto.CompactTextString(m) }
func (*TestListListPrimitiveCom) ProtoMessage()    {}
func (*TestListListPrimitiveCom) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{13}
}
func (m *TestListListPrimitiveCom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestListListPrimitiveCom.Unmarshal(m, b)
}
func (m *TestListListPrimitiveCom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestListListPrimitiveCom.Marshal(b, m, deterministic)
}
func (dst *TestListListPrimitiveCom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestListListPrimitiveCom.Merge(dst, src)
}
func (m *TestListListPrimitiveCom) XXX_Size() int {
	return xxx_messageInfo_TestListListPrimitiveCom.Size(m)
}
func (m *TestListListPrimitiveCom) XXX_DiscardUnknown() {
	xxx_messageInfo_TestListListPrimitiveCom.DiscardUnknown(m)
}

var xxx_messageInfo_TestListListPrimitiveCom proto.InternalMessageInfo

func (m *TestListListPrimitiveCom) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *TestListListPrimitiveCom) GetVal() *PlayerData {
	if m != nil {
		return m.Val
	}
	return nil
}

type TestMapid struct {
	Key                  *int32    `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *BaseInfo `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TestMapid) Reset()         { *m = TestMapid{} }
func (m *TestMapid) String() string { return proto.CompactTextString(m) }
func (*TestMapid) ProtoMessage()    {}
func (*TestMapid) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{14}
}
func (m *TestMapid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMapid.Unmarshal(m, b)
}
func (m *TestMapid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMapid.Marshal(b, m, deterministic)
}
func (dst *TestMapid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMapid.Merge(dst, src)
}
func (m *TestMapid) XXX_Size() int {
	return xxx_messageInfo_TestMapid.Size(m)
}
func (m *TestMapid) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMapid.DiscardUnknown(m)
}

var xxx_messageInfo_TestMapid proto.InternalMessageInfo

func (m *TestMapid) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *TestMapid) GetVal() *BaseInfo {
	if m != nil {
		return m.Val
	}
	return nil
}

type TestMapMapPrimitiveIntInt struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *int32   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMapMapPrimitiveIntInt) Reset()         { *m = TestMapMapPrimitiveIntInt{} }
func (m *TestMapMapPrimitiveIntInt) String() string { return proto.CompactTextString(m) }
func (*TestMapMapPrimitiveIntInt) ProtoMessage()    {}
func (*TestMapMapPrimitiveIntInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{15}
}
func (m *TestMapMapPrimitiveIntInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMapMapPrimitiveIntInt.Unmarshal(m, b)
}
func (m *TestMapMapPrimitiveIntInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMapMapPrimitiveIntInt.Marshal(b, m, deterministic)
}
func (dst *TestMapMapPrimitiveIntInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMapMapPrimitiveIntInt.Merge(dst, src)
}
func (m *TestMapMapPrimitiveIntInt) XXX_Size() int {
	return xxx_messageInfo_TestMapMapPrimitiveIntInt.Size(m)
}
func (m *TestMapMapPrimitiveIntInt) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMapMapPrimitiveIntInt.DiscardUnknown(m)
}

var xxx_messageInfo_TestMapMapPrimitiveIntInt proto.InternalMessageInfo

func (m *TestMapMapPrimitiveIntInt) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *TestMapMapPrimitiveIntInt) GetVal() int32 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type TestMapMapPrimitiveIntStr struct {
	Key                  *int32   `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *string  `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMapMapPrimitiveIntStr) Reset()         { *m = TestMapMapPrimitiveIntStr{} }
func (m *TestMapMapPrimitiveIntStr) String() string { return proto.CompactTextString(m) }
func (*TestMapMapPrimitiveIntStr) ProtoMessage()    {}
func (*TestMapMapPrimitiveIntStr) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{16}
}
func (m *TestMapMapPrimitiveIntStr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMapMapPrimitiveIntStr.Unmarshal(m, b)
}
func (m *TestMapMapPrimitiveIntStr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMapMapPrimitiveIntStr.Marshal(b, m, deterministic)
}
func (dst *TestMapMapPrimitiveIntStr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMapMapPrimitiveIntStr.Merge(dst, src)
}
func (m *TestMapMapPrimitiveIntStr) XXX_Size() int {
	return xxx_messageInfo_TestMapMapPrimitiveIntStr.Size(m)
}
func (m *TestMapMapPrimitiveIntStr) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMapMapPrimitiveIntStr.DiscardUnknown(m)
}

var xxx_messageInfo_TestMapMapPrimitiveIntStr proto.InternalMessageInfo

func (m *TestMapMapPrimitiveIntStr) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *TestMapMapPrimitiveIntStr) GetVal() string {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return ""
}

type TestMapMapPrimitiveStrInt struct {
	Key                  *string  `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Val                  *int32   `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMapMapPrimitiveStrInt) Reset()         { *m = TestMapMapPrimitiveStrInt{} }
func (m *TestMapMapPrimitiveStrInt) String() string { return proto.CompactTextString(m) }
func (*TestMapMapPrimitiveStrInt) ProtoMessage()    {}
func (*TestMapMapPrimitiveStrInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{17}
}
func (m *TestMapMapPrimitiveStrInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMapMapPrimitiveStrInt.Unmarshal(m, b)
}
func (m *TestMapMapPrimitiveStrInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMapMapPrimitiveStrInt.Marshal(b, m, deterministic)
}
func (dst *TestMapMapPrimitiveStrInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMapMapPrimitiveStrInt.Merge(dst, src)
}
func (m *TestMapMapPrimitiveStrInt) XXX_Size() int {
	return xxx_messageInfo_TestMapMapPrimitiveStrInt.Size(m)
}
func (m *TestMapMapPrimitiveStrInt) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMapMapPrimitiveStrInt.DiscardUnknown(m)
}

var xxx_messageInfo_TestMapMapPrimitiveStrInt proto.InternalMessageInfo

func (m *TestMapMapPrimitiveStrInt) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *TestMapMapPrimitiveStrInt) GetVal() int32 {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return 0
}

type TestMapMapPrimitiveStrStr struct {
	Key                  *string  `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Val                  *string  `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestMapMapPrimitiveStrStr) Reset()         { *m = TestMapMapPrimitiveStrStr{} }
func (m *TestMapMapPrimitiveStrStr) String() string { return proto.CompactTextString(m) }
func (*TestMapMapPrimitiveStrStr) ProtoMessage()    {}
func (*TestMapMapPrimitiveStrStr) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{18}
}
func (m *TestMapMapPrimitiveStrStr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMapMapPrimitiveStrStr.Unmarshal(m, b)
}
func (m *TestMapMapPrimitiveStrStr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMapMapPrimitiveStrStr.Marshal(b, m, deterministic)
}
func (dst *TestMapMapPrimitiveStrStr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMapMapPrimitiveStrStr.Merge(dst, src)
}
func (m *TestMapMapPrimitiveStrStr) XXX_Size() int {
	return xxx_messageInfo_TestMapMapPrimitiveStrStr.Size(m)
}
func (m *TestMapMapPrimitiveStrStr) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMapMapPrimitiveStrStr.DiscardUnknown(m)
}

var xxx_messageInfo_TestMapMapPrimitiveStrStr proto.InternalMessageInfo

func (m *TestMapMapPrimitiveStrStr) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *TestMapMapPrimitiveStrStr) GetVal() string {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return ""
}

type TestMapMapPrimitiveIntCom struct {
	Key                  *int32    `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val                  *BaseInfo `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *TestMapMapPrimitiveIntCom) Reset()         { *m = TestMapMapPrimitiveIntCom{} }
func (m *TestMapMapPrimitiveIntCom) String() string { return proto.CompactTextString(m) }
func (*TestMapMapPrimitiveIntCom) ProtoMessage()    {}
func (*TestMapMapPrimitiveIntCom) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{19}
}
func (m *TestMapMapPrimitiveIntCom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMapMapPrimitiveIntCom.Unmarshal(m, b)
}
func (m *TestMapMapPrimitiveIntCom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMapMapPrimitiveIntCom.Marshal(b, m, deterministic)
}
func (dst *TestMapMapPrimitiveIntCom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMapMapPrimitiveIntCom.Merge(dst, src)
}
func (m *TestMapMapPrimitiveIntCom) XXX_Size() int {
	return xxx_messageInfo_TestMapMapPrimitiveIntCom.Size(m)
}
func (m *TestMapMapPrimitiveIntCom) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMapMapPrimitiveIntCom.DiscardUnknown(m)
}

var xxx_messageInfo_TestMapMapPrimitiveIntCom proto.InternalMessageInfo

func (m *TestMapMapPrimitiveIntCom) GetKey() int32 {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return 0
}

func (m *TestMapMapPrimitiveIntCom) GetVal() *BaseInfo {
	if m != nil {
		return m.Val
	}
	return nil
}

type TestMapMapPrimitiveStrCom struct {
	Key                  *string     `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Val                  *PlayerData `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TestMapMapPrimitiveStrCom) Reset()         { *m = TestMapMapPrimitiveStrCom{} }
func (m *TestMapMapPrimitiveStrCom) String() string { return proto.CompactTextString(m) }
func (*TestMapMapPrimitiveStrCom) ProtoMessage()    {}
func (*TestMapMapPrimitiveStrCom) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{20}
}
func (m *TestMapMapPrimitiveStrCom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMapMapPrimitiveStrCom.Unmarshal(m, b)
}
func (m *TestMapMapPrimitiveStrCom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMapMapPrimitiveStrCom.Marshal(b, m, deterministic)
}
func (dst *TestMapMapPrimitiveStrCom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMapMapPrimitiveStrCom.Merge(dst, src)
}
func (m *TestMapMapPrimitiveStrCom) XXX_Size() int {
	return xxx_messageInfo_TestMapMapPrimitiveStrCom.Size(m)
}
func (m *TestMapMapPrimitiveStrCom) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMapMapPrimitiveStrCom.DiscardUnknown(m)
}

var xxx_messageInfo_TestMapMapPrimitiveStrCom proto.InternalMessageInfo

func (m *TestMapMapPrimitiveStrCom) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *TestMapMapPrimitiveStrCom) GetVal() *PlayerData {
	if m != nil {
		return m.Val
	}
	return nil
}

type PlayerData struct {
	BaseInfo             *BaseInfo `protobuf:"bytes,1,opt,name=baseInfo" json:"baseInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PlayerData) Reset()         { *m = PlayerData{} }
func (m *PlayerData) String() string { return proto.CompactTextString(m) }
func (*PlayerData) ProtoMessage()    {}
func (*PlayerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{21}
}
func (m *PlayerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerData.Unmarshal(m, b)
}
func (m *PlayerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerData.Marshal(b, m, deterministic)
}
func (dst *PlayerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerData.Merge(dst, src)
}
func (m *PlayerData) XXX_Size() int {
	return xxx_messageInfo_PlayerData.Size(m)
}
func (m *PlayerData) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerData.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerData proto.InternalMessageInfo

func (m *PlayerData) GetBaseInfo() *BaseInfo {
	if m != nil {
		return m.BaseInfo
	}
	return nil
}

type PlayerInfo struct {
	ServerTime           *int64   `protobuf:"varint,1,opt,name=serverTime" json:"serverTime,omitempty"`
	ServerName           *string  `protobuf:"bytes,2,opt,name=serverName" json:"serverName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{22}
}
func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (dst *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(dst, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetServerTime() int64 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

func (m *PlayerInfo) GetServerName() string {
	if m != nil && m.ServerName != nil {
		return *m.ServerName
	}
	return ""
}

type BaseInfo struct {
	Id                   *int64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name                 *string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Level                *int32   `protobuf:"varint,3,opt,name=level" json:"level,omitempty"`
	Exp                  *int32   `protobuf:"varint,4,opt,name=exp" json:"exp,omitempty"`
	Gold                 *int32   `protobuf:"varint,5,opt,name=gold" json:"gold,omitempty"`
	Head                 *int32   `protobuf:"varint,6,opt,name=head" json:"head,omitempty"`
	Diamond              *int32   `protobuf:"varint,7,opt,name=diamond" json:"diamond,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseInfo) Reset()         { *m = BaseInfo{} }
func (m *BaseInfo) String() string { return proto.CompactTextString(m) }
func (*BaseInfo) ProtoMessage()    {}
func (*BaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{23}
}
func (m *BaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseInfo.Unmarshal(m, b)
}
func (m *BaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseInfo.Marshal(b, m, deterministic)
}
func (dst *BaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseInfo.Merge(dst, src)
}
func (m *BaseInfo) XXX_Size() int {
	return xxx_messageInfo_BaseInfo.Size(m)
}
func (m *BaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BaseInfo proto.InternalMessageInfo

func (m *BaseInfo) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *BaseInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *BaseInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *BaseInfo) GetExp() int32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *BaseInfo) GetGold() int32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func (m *BaseInfo) GetHead() int32 {
	if m != nil && m.Head != nil {
		return *m.Head
	}
	return 0
}

func (m *BaseInfo) GetDiamond() int32 {
	if m != nil && m.Diamond != nil {
		return *m.Diamond
	}
	return 0
}

type TestList struct {
	Id                   *int64                      `protobuf:"varint,7,opt,name=id" json:"id,omitempty"`
	ListPrimitiveInt     []*TestListListPrimitiveInt `protobuf:"bytes,1,rep,name=ListPrimitiveInt" json:"ListPrimitiveInt,omitempty"`
	ListPrimitiveStr     []*TestListListPrimitiveStr `protobuf:"bytes,2,rep,name=ListPrimitiveStr" json:"ListPrimitiveStr,omitempty"`
	ListPrimitiveCom     []*TestListListPrimitiveCom `protobuf:"bytes,3,rep,name=ListPrimitiveCom" json:"ListPrimitiveCom,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *TestList) Reset()         { *m = TestList{} }
func (m *TestList) String() string { return proto.CompactTextString(m) }
func (*TestList) ProtoMessage()    {}
func (*TestList) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{24}
}
func (m *TestList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestList.Unmarshal(m, b)
}
func (m *TestList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestList.Marshal(b, m, deterministic)
}
func (dst *TestList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestList.Merge(dst, src)
}
func (m *TestList) XXX_Size() int {
	return xxx_messageInfo_TestList.Size(m)
}
func (m *TestList) XXX_DiscardUnknown() {
	xxx_messageInfo_TestList.DiscardUnknown(m)
}

var xxx_messageInfo_TestList proto.InternalMessageInfo

func (m *TestList) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *TestList) GetListPrimitiveInt() []*TestListListPrimitiveInt {
	if m != nil {
		return m.ListPrimitiveInt
	}
	return nil
}

func (m *TestList) GetListPrimitiveStr() []*TestListListPrimitiveStr {
	if m != nil {
		return m.ListPrimitiveStr
	}
	return nil
}

func (m *TestList) GetListPrimitiveCom() []*TestListListPrimitiveCom {
	if m != nil {
		return m.ListPrimitiveCom
	}
	return nil
}

type TestMap struct {
	Id                   *BaseInfo                    `protobuf:"bytes,7,opt,name=id" json:"id,omitempty"`
	MapPrimitiveIntInt   []*TestMapMapPrimitiveIntInt `protobuf:"bytes,1,rep,name=MapPrimitiveIntInt" json:"MapPrimitiveIntInt,omitempty"`
	MapPrimitiveIntStr   []*TestMapMapPrimitiveIntStr `protobuf:"bytes,2,rep,name=MapPrimitiveIntStr" json:"MapPrimitiveIntStr,omitempty"`
	MapPrimitiveStrInt   []*TestMapMapPrimitiveStrInt `protobuf:"bytes,3,rep,name=MapPrimitiveStrInt" json:"MapPrimitiveStrInt,omitempty"`
	MapPrimitiveStrStr   []*TestMapMapPrimitiveStrStr `protobuf:"bytes,4,rep,name=MapPrimitiveStrStr" json:"MapPrimitiveStrStr,omitempty"`
	MapPrimitiveIntCom   []*TestMapMapPrimitiveIntCom `protobuf:"bytes,5,rep,name=MapPrimitiveIntCom" json:"MapPrimitiveIntCom,omitempty"`
	MapPrimitiveStrCom   []*TestMapMapPrimitiveStrCom `protobuf:"bytes,6,rep,name=MapPrimitiveStrCom" json:"MapPrimitiveStrCom,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *TestMap) Reset()         { *m = TestMap{} }
func (m *TestMap) String() string { return proto.CompactTextString(m) }
func (*TestMap) ProtoMessage()    {}
func (*TestMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_playerdata_88cdf028b5db25b4, []int{25}
}
func (m *TestMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestMap.Unmarshal(m, b)
}
func (m *TestMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestMap.Marshal(b, m, deterministic)
}
func (dst *TestMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestMap.Merge(dst, src)
}
func (m *TestMap) XXX_Size() int {
	return xxx_messageInfo_TestMap.Size(m)
}
func (m *TestMap) XXX_DiscardUnknown() {
	xxx_messageInfo_TestMap.DiscardUnknown(m)
}

var xxx_messageInfo_TestMap proto.InternalMessageInfo

func (m *TestMap) GetId() *BaseInfo {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *TestMap) GetMapPrimitiveIntInt() []*TestMapMapPrimitiveIntInt {
	if m != nil {
		return m.MapPrimitiveIntInt
	}
	return nil
}

func (m *TestMap) GetMapPrimitiveIntStr() []*TestMapMapPrimitiveIntStr {
	if m != nil {
		return m.MapPrimitiveIntStr
	}
	return nil
}

func (m *TestMap) GetMapPrimitiveStrInt() []*TestMapMapPrimitiveStrInt {
	if m != nil {
		return m.MapPrimitiveStrInt
	}
	return nil
}

func (m *TestMap) GetMapPrimitiveStrStr() []*TestMapMapPrimitiveStrStr {
	if m != nil {
		return m.MapPrimitiveStrStr
	}
	return nil
}

func (m *TestMap) GetMapPrimitiveIntCom() []*TestMapMapPrimitiveIntCom {
	if m != nil {
		return m.MapPrimitiveIntCom
	}
	return nil
}

func (m *TestMap) GetMapPrimitiveStrCom() []*TestMapMapPrimitiveStrCom {
	if m != nil {
		return m.MapPrimitiveStrCom
	}
	return nil
}

func init() {
	proto.RegisterType((*PlayerDatabaseInfo)(nil), "netproto.PlayerDatabaseInfo")
	proto.RegisterType((*PlayerInfoserverTime)(nil), "netproto.PlayerInfoserverTime")
	proto.RegisterType((*PlayerInfoserverName)(nil), "netproto.PlayerInfoserverName")
	proto.RegisterType((*BaseInfoid)(nil), "netproto.BaseInfoid")
	proto.RegisterType((*BaseInfoname)(nil), "netproto.BaseInfoname")
	proto.RegisterType((*BaseInfolevel)(nil), "netproto.BaseInfolevel")
	proto.RegisterType((*BaseInfoexp)(nil), "netproto.BaseInfoexp")
	proto.RegisterType((*BaseInfogold)(nil), "netproto.BaseInfogold")
	proto.RegisterType((*BaseInfohead)(nil), "netproto.BaseInfohead")
	proto.RegisterType((*BaseInfodiamond)(nil), "netproto.BaseInfodiamond")
	proto.RegisterType((*TestListid)(nil), "netproto.TestListid")
	proto.RegisterType((*TestListListPrimitiveInt)(nil), "netproto.TestListListPrimitiveInt")
	proto.RegisterType((*TestListListPrimitiveStr)(nil), "netproto.TestListListPrimitiveStr")
	proto.RegisterType((*TestListListPrimitiveCom)(nil), "netproto.TestListListPrimitiveCom")
	proto.RegisterType((*TestMapid)(nil), "netproto.TestMapid")
	proto.RegisterType((*TestMapMapPrimitiveIntInt)(nil), "netproto.TestMapMapPrimitiveIntInt")
	proto.RegisterType((*TestMapMapPrimitiveIntStr)(nil), "netproto.TestMapMapPrimitiveIntStr")
	proto.RegisterType((*TestMapMapPrimitiveStrInt)(nil), "netproto.TestMapMapPrimitiveStrInt")
	proto.RegisterType((*TestMapMapPrimitiveStrStr)(nil), "netproto.TestMapMapPrimitiveStrStr")
	proto.RegisterType((*TestMapMapPrimitiveIntCom)(nil), "netproto.TestMapMapPrimitiveIntCom")
	proto.RegisterType((*TestMapMapPrimitiveStrCom)(nil), "netproto.TestMapMapPrimitiveStrCom")
	proto.RegisterType((*PlayerData)(nil), "netproto.PlayerData")
	proto.RegisterType((*PlayerInfo)(nil), "netproto.PlayerInfo")
	proto.RegisterType((*BaseInfo)(nil), "netproto.BaseInfo")
	proto.RegisterType((*TestList)(nil), "netproto.TestList")
	proto.RegisterType((*TestMap)(nil), "netproto.TestMap")
}

func init() { proto.RegisterFile("playerdata.proto", fileDescriptor_playerdata_88cdf028b5db25b4) }

var fileDescriptor_playerdata_88cdf028b5db25b4 = []byte{
	// 590 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xcd, 0x8e, 0xd3, 0x3c,
	0x18, 0x85, 0x95, 0xbf, 0x69, 0xf3, 0xf6, 0xfb, 0xa0, 0xb2, 0xba, 0x30, 0x1b, 0x54, 0x05, 0x84,
	0xba, 0xaa, 0x86, 0x22, 0x36, 0x08, 0x81, 0x44, 0xd9, 0x8c, 0xd4, 0x19, 0x8d, 0x92, 0x72, 0x01,
	0x46, 0x31, 0x10, 0x91, 0x3f, 0xb9, 0x56, 0x35, 0x73, 0x0b, 0x5c, 0x01, 0xf7, 0xc0, 0x4d, 0x22,
	0x3b, 0x76, 0x13, 0x12, 0x67, 0xc6, 0x5d, 0x8c, 0xe4, 0x79, 0xd3, 0xe7, 0xf8, 0xe4, 0xd8, 0x39,
	0x30, 0xaf, 0x73, 0x72, 0x4f, 0x59, 0x4a, 0x38, 0x59, 0xd7, 0xac, 0xe2, 0x15, 0x9a, 0x96, 0x94,
	0xcb, 0x55, 0xb4, 0x03, 0x74, 0x2b, 0x9f, 0x7e, 0x26, 0x9c, 0x7c, 0x25, 0x07, 0x7a, 0x55, 0x7e,
	0xab, 0xd0, 0x1c, 0xbc, 0x9f, 0xf4, 0x1e, 0x3b, 0x4b, 0x67, 0x15, 0xc4, 0x62, 0x89, 0x5e, 0x82,
	0x77, 0x24, 0x39, 0x76, 0x97, 0xce, 0x6a, 0xb6, 0x41, 0x6b, 0xcd, 0xaf, 0x3f, 0x29, 0x24, 0x16,
	0x8f, 0xa3, 0x77, 0xb0, 0x68, 0xd4, 0xc4, 0xe8, 0x40, 0xd9, 0x91, 0xb2, 0x7d, 0x56, 0x50, 0x83,
	0xde, 0xbc, 0xd5, 0xf3, 0x46, 0xd9, 0x1b, 0xf2, 0x18, 0x1b, 0x36, 0xec, 0x25, 0x80, 0x36, 0x92,
	0xa5, 0x56, 0xbb, 0x6d, 0xe0, 0x3f, 0x4d, 0x94, 0xb6, 0xbb, 0xbc, 0x81, 0xff, 0x35, 0x93, 0xd3,
	0x23, 0xcd, 0x1f, 0x86, 0x82, 0x06, 0x7a, 0x0d, 0x33, 0x0d, 0xd1, 0xbb, 0xda, 0x0a, 0xe9, 0x78,
	0xfb, 0x5e, 0xe5, 0xe9, 0xb9, 0xcc, 0x0f, 0x4a, 0xec, 0x98, 0xb7, 0xf0, 0x54, 0x33, 0x69, 0x46,
	0x8a, 0xaa, 0xb4, 0xc3, 0x2e, 0x01, 0xf6, 0xf4, 0xc0, 0x77, 0xd9, 0x81, 0x5b, 0x86, 0xfd, 0x01,
	0xb0, 0x26, 0xc4, 0xdf, 0x2d, 0xcb, 0x8a, 0x8c, 0x67, 0x47, 0x7a, 0x55, 0x72, 0xab, 0x1d, 0xc7,
	0xf8, 0x84, 0x33, 0xab, 0x83, 0xdb, 0x8f, 0xf0, 0xdb, 0xaa, 0x30, 0xf0, 0xaf, 0xba, 0x57, 0x7d,
	0xd1, 0x5e, 0xf5, 0xf6, 0x3b, 0x69, 0x54, 0xb7, 0x10, 0x0a, 0xd5, 0x6b, 0x52, 0x1b, 0x63, 0xb0,
	0xfb, 0x62, 0x3e, 0xc2, 0x33, 0x25, 0x72, 0x4d, 0xea, 0x6e, 0x30, 0xb6, 0xd9, 0x8c, 0x0a, 0xd8,
	0x86, 0x63, 0x16, 0x48, 0x38, 0xeb, 0x39, 0x08, 0xcf, 0x73, 0x90, 0x70, 0xd6, 0x73, 0x10, 0x8e,
	0x39, 0x48, 0xc6, 0x5e, 0xc1, 0x7c, 0x3e, 0x76, 0xc1, 0x7e, 0x19, 0x73, 0xd5, 0x13, 0x0d, 0xcf,
	0x3b, 0xf4, 0xf7, 0x00, 0xed, 0x08, 0xad, 0x61, 0xaa, 0x3b, 0x53, 0x8a, 0x99, 0xfd, 0x9c, 0x7e,
	0x13, 0xed, 0x34, 0x2d, 0x5b, 0xf6, 0x39, 0x40, 0xdb, 0x91, 0x92, 0xf7, 0xe2, 0xce, 0xa4, 0x7d,
	0x2e, 0x7a, 0x50, 0x05, 0xd6, 0x99, 0x44, 0xbf, 0x1d, 0x98, 0xea, 0x4d, 0xd0, 0x13, 0x70, 0xb3,
	0x54, 0x89, 0xb8, 0x59, 0x8a, 0x10, 0xf8, 0x65, 0x8b, 0xc9, 0x35, 0x5a, 0x40, 0x20, 0x8b, 0x0b,
	0x7b, 0x32, 0xcd, 0xe0, 0xd4, 0x62, 0xf4, 0xae, 0xc6, 0x7e, 0x93, 0xb0, 0x28, 0x29, 0x04, 0xbe,
	0x28, 0x1e, 0x1c, 0xc8, 0x91, 0x5c, 0x8b, 0x99, 0x28, 0x16, 0x7c, 0xd1, 0xcc, 0x64, 0xc9, 0x60,
	0x98, 0xa8, 0xe2, 0xc0, 0x13, 0x39, 0xd6, 0xff, 0x46, 0xbf, 0x5c, 0x98, 0xea, 0x4f, 0x4e, 0x59,
	0x9b, 0x9c, 0xac, 0xdd, 0xc0, 0xbc, 0x5f, 0x03, 0xd8, 0x59, 0x7a, 0xab, 0xd9, 0x26, 0x6a, 0xd3,
	0x1b, 0x2b, 0x8c, 0x78, 0xc0, 0x0e, 0xf4, 0x12, 0xce, 0xb0, 0x6b, 0xa5, 0x97, 0x70, 0x16, 0x0f,
	0xd8, 0x81, 0xde, 0xb6, 0x2a, 0xb0, 0x67, 0xa5, 0xb7, 0xad, 0x8a, 0x78, 0xc0, 0x46, 0x7f, 0x7c,
	0x98, 0xa8, 0xbb, 0x88, 0xa2, 0x53, 0x16, 0xe6, 0xbb, 0x22, 0xf2, 0x49, 0x00, 0x0d, 0xcb, 0x40,
	0x25, 0xf4, 0xe2, 0x5f, 0x07, 0xc6, 0xde, 0x88, 0x0d, 0xb8, 0x41, 0xb4, 0x8d, 0xe9, 0x51, 0x51,
	0x91, 0x93, 0x01, 0xef, 0x8b, 0x36, 0xa5, 0xa1, 0xb2, 0x7a, 0x58, 0xb4, 0xf9, 0x69, 0x6c, 0xc0,
	0x0d, 0xa2, 0xc2, 0xa9, 0x6f, 0x27, 0x3a, 0x70, 0xaa, 0x7a, 0x68, 0xf8, 0xfa, 0xe2, 0x54, 0x03,
	0xbb, 0xd7, 0x17, 0xc7, 0x6a, 0xc0, 0x0d, 0x4e, 0x85, 0xe8, 0x85, 0x9d, 0xd3, 0x81, 0x68, 0x33,
	0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x39, 0xaf, 0xe7, 0xde, 0xae, 0x09, 0x00, 0x00,
}
